project/api/api/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from rest_framework import routers
from apiapp import views

router = routers.DefaultRouter()
router.register('UsedCar', views.UsedCar) #views.py에서 만들었던 UsedCar클래스를 연동시킵니다. 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(router.urls)),

]

project/apps/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from apps import views
import sys
import io
import cgi
from .forms import *

app_name = 'UsedCar'
urlpatterns = [
    path('', views.main, name = 'main'), #메인페이지를 위한 url
    path('survey', views.survey, name = 'survey'), #메인페이지에서 survey를 누르면 가는 url
    ]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from apps import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls', namespace = 'UsedCar')),
]

project/api/apiapp/models.py
from django.db import models

class UsedCar(models.Model):
    accident_history = models.CharField(max_length = 20, blank=True, default ='')
    repair_history = models.TextField(blank=True, default ='')
    manufacturer = models.CharField(max_length = 20, blank=True,default ='')

    class Meta:
        verbose_name_plural = 'UsedCar'

    def __str__(self):
        return self.id

#전반적으로 apps의 model과 똑같습니다.

project/apps/models.py
from django.db import models

class UsedCar(models.Model):
    accident_history = models.CharField(max_length = 20, blank=True, default ='')
    repair_history = models.TextField(blank=True, default ='')
    manufacturer = models.CharField(max_length = 20, blank=True,default ='')

    class Meta:
        verbose_name_plural = 'UsedCar'

    def __str__(self):
        # admin에서 저장하면 object말고 return값인 id가 출력됩니다.
        # 모델 필드들을 보고 데이터들을 구분하기는 어려워서 id값을 return했습니다. 
        return self.id

project/apps/forms.py
from django import forms
from django.db import models
from .models import UsedCar
class UsedCarForm(forms.ModelForm):

    class Meta:
        model = UsedCar #모델 UsedCar을 받아옵니다.
        fields = ['accident_history', 'repair_history', 'manufacturer'] #모델 UsedCar의 필드 중에서 사용할 필드들을 받아옵니다.

project/api/apiapp/views.py
from django.shortcuts import render
from .models import UsedCar
from django.views import View, generic
from rest_framework import viewsets
from .serializers import UsedCarSerializer
# Create your views here.

class UsedCar(viewsets.ModelViewSet): #rest_framework에서 임포트한 viewsets의 ModelViewSet을 상속/연동합니다.
                                      #ModelViewSet은 서버를 실행하면 화면에 데이터를 출력해서 Read할 수 있게 해줍니다.
    queryset = UsedCar.objects.all()
    serializer_class =  UsedCarSerializer

project/apps/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from apps import models
from apps.forms import *

def main(request):
    return render(request, 'main.html')

def survey(request):
    if request.method == 'POST': #페이지에 POST방식으로 요청할 때(=survey.html에서 form양식을 작성하고 submit했을 때)
        form = UsedCarForm(request.POST) # survey.html에서 form양식을 작성한 값들
        if form.is_valid(): #form양식을 작성한 값들이 형식(models.py에서 정한 형식. e.g., CharField(max_length))에 맞는지 check
            obj = UsedCar(accident_history = form.data['accident_history'], repair_history = form.data['repair_history'],manufacturer = form.data['manufacturer'])
            #obj이라는 변수에 form양식에 작성한 값들을 넣습니다.
            obj.save() #그리고 save합니다.
            return redirect('http://127.0.0.1:8000/') #데이터들은 DB에 저장이되고 화면은 메인페이지로 돌아갑니다.
        return HttpResponse('Failed. Try again.<br>' + 'Go back to the survey -> <a href = "survey">SURVEY</a>')
        #form값이 양식에 맞지 않으면 HttpResponse값이 화면에 출력됩니다.

    elif request.method == 'GET':
    #페이지에 GET방식으로 요청할 때(=메인 페이지의 survey를 눌렸을 때)는 그냥 survey.html템플릿을 return해줍니다.
        form = UsedCarForm()
        return render(request, 'survey.html')
    else:
        pass

project/templates/main.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Bootstrap을 불러오는 링크 -->
    <style>
      body {
        margin: 7px;
      }

      a {
        text-decoration: none;
      }
    </style>
  </head>
  <body>
    <h1 style = "text-align: center; color: blue;"><a href = "{% url 'UsedCar:main' %}">똑똑한 중고차<a></h1>
    <h1>Welcome!</h1>
    Go to survey -> <a href = "{% url 'UsedCar:survey' %}">SURVEY</a>
  </body>
</html>

project/templates/survey.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
        body {
          margin: 7px;
        }
        #manufacturer {
          display: grid;
          grid-template-columns: 100px 100px 100px;
        }

        #manufacturer > button {
          margin: 2px;

        }

        a {
          text-decoration: none;
        }
    </style>
  </head>
  <body>
      <h1 style = "text-align: center; color: blue;"><a href = "{% url 'UsedCar:main' %}">똑똑한 중고차<a></h1>
      <form action="{% url 'UsedCar:survey' %}" method = "post">
        <div class="form-group">
          <label for="accident_history">사고이력</label>
          <input type="text" class="form-control" id="accident_history" name = 'accident_history' placeholder="사고이력의 유무를 적어 주세요." style = "width: 20%">

          <label for="repair_history">수리내역</label>
          <input type="text" class="form-control" id="repair_history" name = 'repair_history' placeholder="구체적인 수리 내역을 작성해 주세요." style = "width: 20%">

          <label for="manufacturer">제조사</label>
          <input type="text" class="form-control" id="manufacturer" name = 'manufacturer' placeholder="자동차의 제조사를 적어 주세요." style = "width: 20%">
            <br>
        </div>
        <input type="submit" class = "btn btn-outline-primary btn-md" value="Submit" name="submit">
        {% csrf_token %}
      </form>

  </body>
</html>

<!-- <h3>사고이력</h3>
<p><textarea placeholder="사고이력의 유무를 적어 주세요." style = "width: 20%"></textarea></p>

<h3>수리내역</h3>
  <p><textarea placeholder="구체적인 수리 내역을 작성해 주세요." style = "width: 20%"></textarea></p>

<h3>제조사</h3>
<p><textarea placeholder="자동차의 제조사를 적어 주세요." style = "width: 20%"></textarea></p> -->

project/templates/survey_OG.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
        body {
          margin: 7px;
        }
        #manufacturer {
          display: grid;
          grid-template-columns: 100px 100px 100px;
        }

        #manufacturer > button {
          margin: 2px;

        }

        a {
          text-decoration: none;
        }
    </style>
  </head>
  <body>
    <!-- 제플린보고 따라했던 첫 템플릿.. -->
    <form>
      <h1 style = "text-align: center; color: blue;"><a href = "http://127.0.0.1:8000/">똑똑한 중고차<a></h1>
      <h3>사고이력</h3>
      <button class = "btn btn-outline-primary btn-md" value = "Accident Found">사고 이력 있음</button>
      <button class = "btn btn-outline-primary btn-md" value = "No Accident Found">사고 이력 없음</button>
      <br><br>

      <h3>수리내역</h3>
        <p><textarea placeholder="구체적인 수리 내역을 작성해 주세요." style = "width: 20%"></textarea></p>

      <h3>제조사</h3>
      <div id = "manufacturer">
        <button class = "btn btn-outline-primary btn-md" value = "Create">현대</button>
        <button class = "btn btn-outline-primary btn-md" value = "Create">르노 삼성</button>
        <button class = "btn btn-outline-primary btn-md" value = "Create">기아</button>
        <button class = "btn btn-outline-primary btn-md" value = "Create">쌍용</button>
        <button class = "btn btn-outline-primary btn-md" value = "Create">GM 대우</button>
        <button class = "btn btn-outline-primary btn-md" value = "Create">기타</button>
      </div>
      <br>
    <p><input type="submit" value="Submit"></p>
    </form>

  </body>
</html>